variable "COMPONENT" {}
variable "ENV" {}
variable "INTERNAL" {}
variable "APP_VERSION" {}
variable "APP_PORT" {}
variable "SPOT_INSTANCE" {}
variable "SPOT_INSTANCE_COUNT" {}
variable "OD_INSTANCE" {}
variable "OD_INSTANCE_COUNT" {}